# This is a basic workflow to help you get started with Actions

name: Terraform CI

# Controls when the workflow will run
on:
  push:
    branches: '**'

  pull_request:
    branches: [ "main" ]

  # Allows to run this workflow manually from the Actions tab
  #workflow_dispatch:

# Required for aws-actions
permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_GITHUB_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Plan
        id: plan
        run: |
          terraform init
          terraform plan -no-color

